<a href="https://colab.research.google.com/github/nicoleyauri9/ccny-calendar-scraper/blob/main/ccny_calendar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [37]:
with open("Fall 2021 Academic Calendar.html", "r", encoding="utf-8") as file:
    html_doc = file.read()

soup = BeautifulSoup(html_doc, "html.parser")
table = soup.find("table")

In [25]:
rows = table.find_all("tr")

dates = []
dows = []
texts = []

for row in rows:
    cells = row.find_all("td")

    if len(cells) == 3:
        dates.append(cells[0].get_text(" ", strip=True))
        dows.append(cells[1].get_text(" ", strip=True))
        texts.append(cells[2].get_text(" ", strip=True))

print(dates[:5])
print(dows[:5])
print(texts[:5])

['August 01', 'August 18', 'August 24', 'August 25', 'August 25 - 31']
['Sunday', 'Wednesday', 'Tuesday', 'Wednesday', 'Wednesday - Tuesday']
['Application for degree for January and February 2022 begins', 'Last day to apply for Study Abroad', 'Last day of Registration; Last day to file ePermit for the Fall 2021; Last day to drop classes for 100% tuition refund;', 'Start of Fall Term; Classes begin; Initial Registration Appeals begin;', 'Change of program period; late fees apply']

In [26]:
df = pd.DataFrame({
    "date": dates,
    "dow": dows,
    "text": texts
})

df.head()

,date,dow,text
0,August 01,Sunday,Application for degree for January and Februar...
1,August 18,Wednesday,Last day to apply for Study Abroad
2,August 24,Tuesday,Last day of Registration; Last day to file ePe...
3,August 25,Wednesday,Start of Fall Term; Classes begin; Initial Reg...
4,August 25 - 31,Wednesday - Tuesday,Change of program period; late fees apply

In [29]:
df["date_clean"] = df["date"]

df.head()

,date,dow,text,date_clean
0,August 01,Sunday,Application for degree for January and Februar...,August 01
1,August 18,Wednesday,Last day to apply for Study Abroad,August 18
2,August 24,Tuesday,Last day of Registration; Last day to file ePe...,August 24
3,August 25,Wednesday,Start of Fall Term; Classes begin; Initial Reg...,August 25
4,August 25 - 31,Wednesday - Tuesday,Change of program period; late fees apply,August 25 - 31

In [30]:
df["date_clean"] = df["date_clean"].str.split(" - ").str[0]

df[["date", "date_clean"]].head(10)

                date    date_clean
0          August 01     August 01
1          August 18     August 18
2          August 24     August 24
3          August 25     August 25
4     August 25 - 31     August 25
5          August 26     August 26
6          August 28     August 28
7          August 31     August 31
8       September 01  September 01
9  September 03 - 08  September 03

In [31]:
df["date_clean"] = df["date_clean"].apply(
    lambda x: x if "2022" in x else x + " 2021"
)

df[["date", "date_clean"]].tail()

                date        date_clean
31  December 24 - 25  December 24 2021
32       December 27  December 27 2021
33       December 28  December 28 2021
34       December 31  December 31 2021
35   January 1, 2022   January 1, 2022

In [33]:
df["date_clean"] = pd.to_datetime(df["date_clean"], format="mixed").dt.date

type(df["date_clean"].iloc[0])

datetime.date

In [34]:
df = df.set_index("date_clean")

df.head()

,date,dow,text
date_clean,,,
2021-08-01,August 01,Sunday,Application for degree for January and Februar...
2021-08-18,August 18,Wednesday,Last day to apply for Study Abroad
2021-08-24,August 24,Tuesday,Last day of Registration; Last day to file ePe...
2021-08-25,August 25,Wednesday,Start of Fall Term; Classes begin; Initial Reg...
2021-08-25,August 25 - 31,Wednesday - Tuesday,Change of program period; late fees apply

In [38]:
df = df[["dow", "text"]]

df.index.name = "date"

df

,dow,text
date,,
2021-08-01,Sunday,Application for degree for January and Februar...
2021-08-18,Wednesday,Last day to apply for Study Abroad
2021-08-24,Tuesday,Last day of Registration; Last day to file ePe...
2021-08-25,Wednesday,Start of Fall Term; Classes begin; Initial Reg...
2021-08-25,Wednesday - Tuesday,Change of program period; late fees apply
2021-08-26,Thursday,Last day for Independent Study
2021-08-28,Saturday,First day of Saturday Classes
2021-08-31,Tuesday,Last day to add a class to an existing enrollm...
2021-09-01,Wednesday,Verification of Enrollment rosters available t...
2021-09-03,Friday - Wednesday,No classes scheduled
2021-09-06,Monday,College Closed; Last day for 50% tuition refund;
2021-09-09,Thursday,Freshman Convocation
2021-09-14,Tuesday,Last day for 25% tuition refund; Census date; ...
2021-09-15,Wednesday,Assignment of 'WN' grades for non-attendance; ...
2021-09-15,Wednesday - Thursday,No classes scheduled
2021-09-23,Thursday,Last day to submit proof of immunization for N...
2021-09-24,Friday,Assignment of 'WA' grades for immunization non...
2021-10-01,Friday,Advising month begins for Spring and Winter en...
2021-10-08,Friday,Deadline for filing application for degree for...
2021-10-11,Monday,College Closed
2021-11-01,Monday,'INC' grades for Spring 2021 and Winter 2021 f...
2021-11-02,Tuesday,Registration appointments for Winter and Sprin...
2021-11-04,Thursday,Last day to file for P/NC option
2021-11-06,Saturday,60% Date of the term
2021-11-23,Tuesday,'INC' grades for Summer 2021 for Undergraduate...
2021-11-25,Thursday - Sunday,College Closed
2021-12-11,Saturday,Last day of Saturday Classes
2021-12-13,Monday,Course Withdrawal period ends (Last day to wit...
2021-12-14,Tuesday,Reading Day
2021-12-15,Wednesday - Tuesday,Final Examinations
2021-12-21,Tuesday,End of Term
2021-12-24,Friday - Saturday,College Closed
2021-12-27,Monday,College Closed
2021-12-28,Tuesday,Final Grade Submission Deadline for Fall 2021
2021-12-31,Friday,College Closed
2022-01-01,Saturday,College Closed; Fall 2021 Degree Conferral Date;